apiVersion: v1
kind: Service
metadata:
  name: aoc-leaderboard-scraper
  labels:
    app: aoc-leaderboard-scraper
spec:
  type: ClusterIP
  selector:
    app: aoc-leaderboard-scraper
  ports:
    - port: 3333
      name: main
      protocol: TCP
      targetPort: 3333
    - port: 3334
      name: health
      protocol: TCP
      targetPort: 3334
